---

- src: https://github.com/vid-uo/ansible-role-homebrew.git
  name: vid.superlumic-uo-homebrew

- src: https://github.com/vid-uo/ansible-role-osx-defaults.git
  name: vid.superlumic-uo-osx-defaults

- src: https://github.com/vid-uo/ansible-role-computername.git
  name: vid.superlumic-uo-computername

- src: https://github.com/vid-uo/ansible-role-cli.git
  name: vid.superlumic-uo-cli

- src: https://github.com/vid-uo/ansible-role-mysql.git
  name: vid.superlumic-uo-mysql

- src: https://github.com/vid-uo/ansible-role-php.git
  name: vid.superlumic-uo-php

- src: https://github.com/vid-uo/ansible-role-sublimetext.git
  name: vid.superlumic-uo-sublimetext

- src: https://github.com/vid-uo/ansible-role-node.git
  name: vid.superlumic-uo-node

- src: https://github.com/vid-uo/ansible-role-postgresql.git
  name: vid.superlumic-uo-postgresql

- src: https://github.com/vid-uo/ansible-role-vim.git
  name: vid.superlumic-uo-vim

- src: https://github.com/vid-uo/ansible-role-modjk.git
  name: vid.superlumic-uo-modjk

- src: https://github.com/vid-uo/ansible-role-skylab.git
  name: vid.superlumic-uo-skylab
