---
galaxy_info:
  author: [Author Name]
  description: Ansible profile role for all users
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - vid.superlumic-computername
  - vid.superlumic-cli
