---

- name: tap homebrew/cask-versions
  homebrew_tap: tap=homebrew/cask-versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - pwgen
    - xmlstarlet
    #- htop #not compatible with Mac OS 10.13?
    - watch
    - rsync

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    #- docker-toolbox # for older Macs
    #- phpstorm
    #- webstorm
    - sequel-pro
    #- java
