---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: tap codekitchen/dinghy
  homebrew_tap: tap=codekitchen/dinghy state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - pwgen
    - xmlstarlet
    - htop
    - watch
    - rsync
    - dinghy
    #- docker
    #- docker-machine
    #- docker-machine-driver-xhyve

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - docker-tollbox
    - phpstorm
    - sequel-pro
    - java
    - iterm2-beta
    
# Not using docker xhyve
#- name: set xhyve permissions
#  shell: chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve && chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
#  become: yes
